skillMetadata:
  sections:
    - name: Samsung TV
      fields:
        - name: tv
          type: text
          label: Standard TV (IP 1)
          value:
          placeholder: localhost
        - name: port
          type: number
          label: Port
          value: 55000
          placeholder: 55000
        - name: placement
          type: text
          label: Placement
          value: Stube
          placeholder: room1
        - name: method
          type: text
          label: Method
          value: legacy
          placeholder: legacy
        - name: tvname
          type: text
          label: Name
          value: Mycroft
        - name: description
          type: text
          label: Description
          value: Description
          placeholder: Description
        - name: translations
          type: text
          label: Your words for left, right, up, down, enter and leave
          value:
          placeholder: left,right,up,down,enter,leave



